### ISSUE TITLE
Process string array help needed

### ISSUE THREAD

**Issue by AshwinKamathB** [nhibernate/nhibernate.github.io#10]
We used Nhiberante to store sting[] in one of the column. There is an application where we want to read the same data without using Nhibernate. Table column type is varbinary(max).How i can convert back in C#.Its very critical for me.Please help me. We are using ASP.net core hence i dint use Nhibernate

**Comment by ayende** [comment]
IIRC, this is just binary serialization, try that.

**Comment by AshwinKamathB** [comment]
Example please .Blob conversion.
I am seeing so many extra characters

**Comment by hazzik** [comment]
Hi, this is not a question forum. This is the support board for the functionality of the site. Please forward your questions to the nhusers@googlegroups.com mailing list.
