### ISSUE TITLE
Contributing to Nhibernate

### ISSUE THREAD

**Issue by CGGSanjeeev** [nhibernate/nhibernate.github.io#11]
We are active users of nhibernate and while using we have added some changes which includes bug fix and a new feature which our team think should be submitted back to the nhibernate code set. How can I submit the changes?
I have done below steps but it says permission denied.
 - Took the latest code from Github. (using source tree)
 - Made a specific change to a file. 
 - Tried committing the changes. Got "Permission denied error"

Please guide us so that current and future changes can be submitted

**Comment by gliljas** [comment]
https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md

2017-09-28 8:23 GMT+02:00 CGGSanjeeev <notifications@github.com>:
