### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by fredericDelaporte** [nhibernate/nhibernate.github.io#20]
GitHub pages have gained https support for custom domains, since May 2018. But depending on how the custom domain DNS is setup, it may require some work to enable it.

And it looks like `nhibernate.info` needs some work.

According to the [announcement](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/):

- > [If you are using `CNAME` or `ALIAS` records for your custom domain, you’re all set and your site should be accessible over HTTPS.](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain)

  Well, that is the case for `www.nhibernate.info`, it uses a `CNAME`, but https://www.nhibernate.info fails.

- > If you are using `A` records, you must update your site’s DNS records with new IP addresses. Please [see our guide to setting up your custom domain with Pages and update any A records you might have set](https://help.github.com/articles/setting-up-an-apex-domain/).

  `nhibernate.info` uses `A` records, so they would need some update.

Checking `nhibernate.info` records seems actually not up-to-date. They points:
```
nhibernate.info.	3019	IN	A	192.30.252.153
nhibernate.info.	3019	IN	A	192.30.252.154
```

While it should be according to [Setting up an apex domain](https://help.github.com/articles/setting-up-an-apex-domain/):
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

Updating them will not be enough according to the previous page:

> If you're updating the IP address of an existing `A` record, first remove and then re-add your custom domain to the repository you’re using to publish your Pages site to trigger the process of enabling HTTPS.

So after the change has propagated, it will be likely needed to do that manipulation. Hopefully it will also fix the `www.nhibernate.info` case.

After that, and if that works, we could decide to enforce usage of HTTPS, redirecting HTTP to HTTPS thanks to a GitHub option. I think it should be done.

Registrar data seems to tell that is Oskar who handles the DNS. @oskarb?

**Comment by fredericDelaporte** [comment]
Well, there is also this warning in nhibernate.github.io settings:

> The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/. 

So we anyway need to update those IP, or else the site may go down I fear.

**Comment by oskarb** [comment]
Thanks for the detective work @fredericDelaporte! I've just updated the DNS master records but it seems to take some time before the provider's public servers are updated (this is faster than the regular TTL). Then of course the is the one hour TTL after that.

**Comment by fredericDelaporte** [comment]
Thanks Oskar,

https://nhibernate.info now works.

That is not the case for https://www.nhibernate.info. But it seems "normal", I have found this [here](https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/):

> **Warning:** If your domain has HTTPS enforcement enabled, GitHub Pages' servers will not automatically route redirects. You must configure `www` subdomain and root domain redirects with your domain registrar.

In other words, for having https://www.nhibernate.info properly redirected, we would need our own site doing the redirect.
Some registrar handles this kind of option themselves at least for http, but I do not know if nhibernate.info registrar has such an option and if it has it for https too.
So I guess we will not get https://www.nhibernate.info working. But I do not think this is really an issue. (And maybe at some point in the future GitHub pages will handle it itself.)

This said, I think we need to merge #21 before enforcing https. Then we could close this issue.

Does anyone disagree with enforcing https?

**Comment by oskarb** [comment]
That's unfortunate. Trying https://nhibernate.info reveals a correct but non-wildcard certificate, and trying https://www.nhibernate.info just gives you Github's own certificate which is why the browser won't accept it. Seems like an odd restriction on Github's part, it's not immediately obvious to me why they couldn't serve a proper certificate and a redirect for the www. Perhaps it is as you speculate, that it's not a technical problem, more that they just haven't put in the time to implement it.

I'll check with the registrar, they have some redirect options but I don't know if it works with https - and in any case it would require an nhibernate.info certificate there as well.

**Comment by hazzik** [comment]
Works now. 

https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider

>Add your custom domain to your GitHub Pages site. *If you're updating the IP address of an existing A record, first remove and then re-add your custom domain to the repository you’re using to publish your Pages site to trigger the process of enabling HTTPS. For more information, see "Adding or removing a custom domain for your GitHub Pages site."*

**Comment by fredericDelaporte** [comment]
Great, so the warning I have quoted is not up-to-date. Thanks for the manipulation.

**Comment by oskarb** [comment]
Technically, the warning says "HTTPS *enforcement*" - which is not activated yet. On the other hand if the redirect works for voluntary HTTPS it would be even stranger for it to fail with enforced HTTPS.

**Comment by fredericDelaporte** [comment]
I think the site is ready for switching to https enforced. Is anyone against doing the switch?

**Comment by oskarb** [comment]
Fine by me.

Den tors 13 dec. 2018 kl 12:36 skrev Frédéric Delaporte <
notifications@github.com>:

**Comment by fredericDelaporte** [comment]
Done.
