### ISSUE TITLE
Add reference (and API) docs for past versions

### ISSUE THREAD

**Issue by kenny-evitt** [nhibernate/nhibernate.github.io#7]
I'm willing to submit a pull request with changes pertaining to this. I'd like to at least add the older version I'm using (3.3.3) in a project I maintain (and actively develop).

If you're open to this, I'll generate the reference docs for the version I'm using and take a stab at finding a suitable place in the site structure for it.

I'll also add instructions for others to add other versions. I could also do this myself, as time permits.

If you're open to adding API docs too, I'll investigate a suitable tool for automatically generating them.

**Comment by oskarb** [comment]
I think it can be a good idea.

Some sites that do this add a banner (shown on every page) that point out that you are not currently seeing the latest version. Something similar would be useful if possible.

**Comment by kenny-evitt** [comment]
@oskarb Great. I agree about including the relevant version at the top of the page.

**Comment by kenny-evitt** [comment]
Note to self – [the tags](https://github.com/nhibernate/nhibernate-core/tags) in [the core repo](https://github.com/nhibernate/nhibernate-core) with "GA" are (probably) for 'general availability' releases. I'm guesing "CR" means 'candidate [for] release' and "SP" is 'service pack'. I'm going to ignore, or at least defer, adding docs for the release candidate and alpha tags/releases.
