### ISSUE TITLE
Link on website out of date

### ISSUE THREAD

**Issue by roryap** [nhibernate/nhibernate.github.io#9]
I just wanted to point out that the [here](http://www.hibernate.org/hib_docs/nhibernate/1.2/reference/en/html/mapping.html) link in the "Defining the Mapping Section on [this page](http://nhibernate.info/doc/tutorials/first-nh-app/your-first-nhibernate-based-application.html) is out of date.

**Comment by oskarb** [comment]
Thanks, I've fixed it.

Please note that I think you should be able to provide a suggested edit as a pull request directly through the Github web site.
